# 単体法による線形計画問題の解法
ここでは、単体法を用いて次の線形計画問題を解くことを考えましょう。
\begin{align*}
\text{Minimize }
& c^\top x\\
\text{subject to }
& Ax\le b,\\
& x\ge 0,
\end{align*}
ただし、
\begin{align*}
c&:=(-1, 4)^\top,\\
A&:=\begin{pmatrix}
-3 & 1\\
1 & 2
\end{pmatrix},\\
b&:=(6, 4)^\top
\end{align*}
とします。

単体法による線形計画問題の最適化は、Anaconda に標準で付属しているSciPy に実装されています。
今回は、これを用いて最適化を行いましょう。

まずは、ベクトル$c\in\mathbb{R}^n$、行列$A\in\mathbb{R}^{m\times n}$、ベクトル$b\in\mathbb{R}^m$ をそれぞれNumPy 行列として表現します。

In [1]:
import numpy as np

c = np.array([-1, 4])
A = np.array([[-3, 1],
              [ 1, 2]])
b = np.array([6, 4])

続いて、`callback` 関数を実装します。
通常の線形計画問題の最適化では、この実装は不要ですが、ここでは単体法の途中過程を表示するためにこれを用意します。

In [2]:
def callback(xk: np.ndarray, **kwargs):
    print('===== Iteration #%d =====' % kwargs['nit'])
    print('Current: %s' % xk)
    print('Tableau:')
    print(kwargs['tableau'])
    print()

SciPy に実装される線形計画ソルバは、`scipy.optimize.linprog` として提供されます。
ここでは、このソルバをインポートし、先に用意した各NumPy 行列を渡して単体法による最適化を実行します。
ここで、各変数の上下限は、キーワード引数`bounds` として与えます(`None` は制限しないことを表します)。

In [3]:
from scipy.optimize import linprog

linprog(c, A, b, bounds=(0, None), method='simplex', callback=callback)

===== Iteration #0 =====
Current: [0. 0.]
Tableau:
[[-3.  1.  1.  0.  6.]
 [ 1.  2.  0.  1.  4.]
 [-1.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

===== Iteration #0 =====
Current: [0. 0.]
Tableau:
[[-3.  1.  1.  0.  6.]
 [ 1.  2.  0.  1.  4.]
 [-1.  4.  0.  0.  0.]]

===== Iteration #1 =====
Current: [4. 0.]
Tableau:
[[ 0.  7.  1.  3. 18.]
 [ 1.  2.  0.  1.  4.]
 [ 0.  6.  0.  1.  4.]]



     fun: -4.0
 message: 'Optimization terminated successfully.'
     nit: 1
   slack: array([18.,  0.])
  status: 0
 success: True
       x: array([4., 0.])

## 参考文献
  * The SciPy community: [SciPy v1.1.0 Reference Guide](https://docs.scipy.org/doc/scipy/reference/index.html).